---
title: "Determinanten und Effekte von Kooperation in homogenen und heterogenen Forschungsverbünden"
short-title: "Daten- und Methodenbericht des quantitativen Websurveys"
author:
- Malte Hückstädt
- Luca Marie Leisten
date: "August 2020"
doc-type: "Daten- und Methodenbericht"
lang: de
bibliography: Bibliography.bib
editor_options:
  chunk_output_type: console
output:
  bookdown::pdf_document2:
    fig_caption: yes
    toc: yes
    toc_depth: 5
    keep_tex: false
    template: latex_template_de.tex
    latex_engine: lualatex
    citation_package: biblatex
    number_sections: false
  # bookdown::word_document2:
  #   fig_caption: yes
---

# Motivation

Here some text about diamonds.

## Analysis


### Erstellung eigener Funktionen

Da keine kompakte R-Funktion für die Fusionierung redundanter Spaltenvektoren besteht, die Spaltenvektoren fusioniert, die fusionierte Variable umbenennt sowie die Ursprungsvariablen aus dem Datensatz entfernt, wird eine entsprechende Funktion im folgenden selbst geschrieben. Diese Funktion soll konkret folgende Subfunktionen aufweisen:

1. Die `NA`s zweier Spaltenvektoren werden durch leere Strings ersetzt.

2. Diese beiden Spaltenvektoren werden mittels paste-Funktion zusammengezogen zu einem neuen Spaltenvektor, welchem ein neuer Name (Variablenname) gegeben werden kann.

3. Die neue Variable wird an den Input-Dateframe gemerget.

Diese Funktion wird für den Fall geschrieben, dass zwei (`unite_col`), drei (`unite_col_3`) oder vier drei (`unite_col_4`) Spaltenvektoren zusammengezogen werden sollen.

# References
